# Generated by Django 5.1.5 on 2025-02-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_courses', '0002_group_edit_permissions_joinrequest'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('title', 'course')},
        ),
    ]
